// Hyperliquid signing, ported from the official Python SDK
// (hyperliquid-python-sdk 0.24.0, hyperliquid/utils/signing.py):
//
//   L1 actions (orders, cancels, leverage) — signed by the browser agent key:
//     connectionId = keccak(msgpack(action) ‖ nonce:u64be ‖ 0x00 | 0x01‖vault ‖ [0x00 ‖ expiresAfter:u64be])
//     EIP-712 { domain: Exchange/1/chainId 1337/0x0, Agent{source:"a"|"b", connectionId} }
//   User-signed actions (approveAgent, withdraw3) — signed by the wallet:
//     EIP-712 { domain: HyperliquidSignTransaction/1/<signatureChainId>/0x0, HyperliquidTransaction:<Kind>{…} }
//
// tests/unit/hl-signing.test.ts checks these against the SDK's own known-answer
// vectors (tests/signing_test.py) and against vectors generated by the SDK.

import { getBytes, hexlify, keccak256, recoverAddress, Signature, SigningKey, TypedDataEncoder, concat, zeroPadValue, toBeHex } from "ethers";
import { packb, type Packable } from "./msgpack.ts";

export const ZERO = "0x0000000000000000000000000000000000000000";
export const L1_DOMAIN = { name: "Exchange", version: "1", chainId: 1337, verifyingContract: ZERO } as const;
export const AGENT_TYPES = { Agent: [{ name: "source", type: "string" }, { name: "connectionId", type: "bytes32" }] };
const DOMAIN_FIELDS = [
  { name: "name", type: "string" },
  { name: "version", type: "string" },
  { name: "chainId", type: "uint256" },
  { name: "verifyingContract", type: "address" },
];

export interface HlSig {
  r: string;
  s: string;
  v: number;
}

const u64 = (n: number | bigint) => zeroPadValue(toBeHex(BigInt(n)), 8);

/** keccak(msgpack(action) ‖ nonce ‖ vault flag[‖ vault] [‖ 0x00 ‖ expiresAfter]). */
export function actionHash(action: Packable, vault: string | null, nonce: number, expiresAfter: number | null = null): string {
  const parts: (Uint8Array | string)[] = [packb(action), u64(nonce)];
  if (!vault) parts.push("0x00");
  else parts.push("0x01", getBytes(vault));
  if (expiresAfter !== null && expiresAfter !== undefined) parts.push("0x00", u64(expiresAfter));
  return keccak256(concat(parts));
}

export const phantomAgent = (hash: string, mainnet: boolean) => ({ source: mainnet ? "a" : "b", connectionId: hash });

/** The EIP-712 digest an L1 action is signed over. */
export function l1Digest(action: Packable, nonce: number, mainnet: boolean, vault: string | null = null, expiresAfter: number | null = null): string {
  return TypedDataEncoder.hash(L1_DOMAIN, AGENT_TYPES, phantomAgent(actionHash(action, vault, nonce, expiresAfter), mainnet));
}

export function splitSig(sig: string): HlSig {
  const s = Signature.from(sig);
  return { r: s.r, s: s.s, v: s.v };
}

/** Sign an L1 action with a raw key (the in-memory agent; never the user's wallet key). */
export function signL1(key: SigningKey, action: Packable, nonce: number, mainnet: boolean, vault: string | null = null, expiresAfter: number | null = null): HlSig {
  const sig = key.sign(l1Digest(action, nonce, mainnet, vault, expiresAfter));
  return { r: sig.r, s: sig.s, v: sig.v };
}

export function recoverL1(action: Packable, sig: HlSig, nonce: number, mainnet: boolean, vault: string | null = null, expiresAfter: number | null = null): string {
  return recoverAddress(l1Digest(action, nonce, mainnet, vault, expiresAfter), Signature.from({ r: sig.r, s: sig.s, v: sig.v }));
}

// ---------- user-signed actions ----------

export type UserTypes = { name: string; type: string }[];
export const APPROVE_AGENT_TYPES: UserTypes = [
  { name: "hyperliquidChain", type: "string" },
  { name: "agentAddress", type: "address" },
  { name: "agentName", type: "string" },
  { name: "nonce", type: "uint64" },
];
export const WITHDRAW_TYPES: UserTypes = [
  { name: "hyperliquidChain", type: "string" },
  { name: "destination", type: "string" },
  { name: "amount", type: "string" },
  { name: "time", type: "uint64" },
];

export interface UserTyped {
  domain: { name: string; version: string; chainId: number; verifyingContract: string };
  types: Record<string, UserTypes>;
  primaryType: string;
  message: Record<string, unknown>;
}

/** Typed data for a user-signed action. signatureChainId is the chain the wallet is on (any chain works). */
export function userTyped(primaryType: string, types: UserTypes, action: Record<string, unknown>): UserTyped {
  const chainId = parseInt(String(action.signatureChainId), 16);
  if (!Number.isInteger(chainId) || chainId <= 0) throw new Error("signatureChainId must be a hex chain id");
  const message: Record<string, unknown> = {};
  for (const f of types) message[f.name] = action[f.name];
  return { domain: { name: "HyperliquidSignTransaction", version: "1", chainId, verifyingContract: ZERO }, types: { [primaryType]: types }, primaryType, message };
}

export const userDigest = (t: UserTyped) => TypedDataEncoder.hash(t.domain, t.types, t.message);

/** The JSON eth_signTypedData_v4 expects (EIP712Domain spelled out). */
export function walletPayload(t: UserTyped): string {
  // integers as decimal strings: MetaMask mobile rejects JSON numbers in typed-data messages; the hash is identical
  const message: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(t.message)) message[k] = typeof v === "number" || typeof v === "bigint" ? String(v) : v;
  return JSON.stringify({ domain: t.domain, types: { EIP712Domain: DOMAIN_FIELDS, ...t.types }, primaryType: t.primaryType, message });
}

export function recoverUser(t: UserTyped, sig: HlSig): string {
  return recoverAddress(userDigest(t), Signature.from({ r: sig.r, s: sig.s, v: sig.v }));
}

export const hexChainId = (id: number) => "0x" + id.toString(16);

/** approveAgent action (field order as the Python SDK sends it). Name ≤ 16 chars, optional " valid_until <ms>". */
export function approveAgentAction(o: { mainnet: boolean; chainId: number; agent: string; name: string; nonce: number }) {
  return {
    type: "approveAgent",
    signatureChainId: hexChainId(o.chainId),
    hyperliquidChain: o.mainnet ? "Mainnet" : "Testnet",
    agentAddress: o.agent,
    agentName: o.name,
    nonce: o.nonce,
  };
}

/** withdraw3 action: USDC from the Hyperliquid perps balance to `destination` on Arbitrum (validators pay out, $1 fee). */
export function withdrawAction(o: { mainnet: boolean; chainId: number; destination: string; amount: string; time: number }) {
  if (!/^\d+(\.\d+)?$/.test(o.amount)) throw new Error("amount must be a plain decimal string");
  return { type: "withdraw3", signatureChainId: hexChainId(o.chainId), hyperliquidChain: o.mainnet ? "Mainnet" : "Testnet", destination: o.destination, amount: o.amount, time: o.time };
}

export const hexBytes = (b: Uint8Array) => hexlify(b);
